name: Build Vue App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show files
        run: ls -la

      - name: Run custom action
        uses: ./.github/actions/echo-stuff

      - name: Show files again
        run: ls -la